# Generated by Django 5.2.4 on 2025-07-11 12:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIEndpointRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief title for the API endpoint', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of what this endpoint should do')),
                ('endpoint_path', models.CharField(blank=True, help_text='Suggested endpoint path (e.g., /api/v1/new-feature/)', max_length=100)),
                ('http_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='POST', help_text='Expected HTTP method', max_length=10)),
                ('expected_input', models.TextField(blank=True, help_text='Description of expected input data/parameters')),
                ('expected_output', models.TextField(blank=True, help_text='Description of expected output/response format')),
                ('business_justification', models.TextField(help_text='Why is this endpoint needed? What business problem does it solve?')),
                ('use_case', models.TextField(help_text='How will this endpoint be used? Provide specific examples.')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Priority level for this request', max_length=10)),
                ('date_needed', models.DateField(help_text='When do you need this endpoint to be available?')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=15)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes from admin/development team')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoint_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Endpoint Request',
                'verbose_name_plural': 'API Endpoint Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
