# Generated by Django 5.2.4 on 2025-07-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiendpointrequest',
            name='requester',
            field=models.CharField(blank=True, help_text='Who made the request', max_length=100, null=True),
        ),
    ]
