# Generated by Django 5.2.4 on 2025-07-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_apiendpointrequest_requester'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiendpointrequest',
            name='developed_endpoint_url',
            field=models.URLField(blank=True, help_text='The actual endpoint URL after development is complete', null=True),
        ),
    ]
