# Generated by Django 5.2.4 on 2025-07-11 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_apiendpointrequest_developed_endpoint_url'),
    ]

    operations = [
        migrations.RunSQL(
            "DROP TABLE IF EXISTS web_apiendpointrequest;",
            reverse_sql="-- Cannot reverse table deletion",
        ),
    ]
