# Generated by Django 5.2.4 on 2025-07-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20250711_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiendpointrequest',
            name='business_justification',
            field=models.TextField(blank=True, help_text='Why is this endpoint needed? What business problem does it solve?'),
        ),
        migrations.AlterField(
            model_name='apiendpointrequest',
            name='expected_input',
            field=models.TextField(help_text='Description of expected input data/parameters'),
        ),
        migrations.AlterField(
            model_name='apiendpointrequest',
            name='expected_output',
            field=models.TextField(help_text='Description of expected output/response format'),
        ),
        migrations.AlterField(
            model_name='apiendpointrequest',
            name='use_case',
            field=models.TextField(blank=True, help_text='How will this endpoint be used? Provide specific examples.'),
        ),
    ]
