# Generated by Django 5.2.4 on 2025-07-11 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processinghistory',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='processinghistory',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='processinghistory',
            name='filename',
        ),
    ]
