# Generated by Django 5.2.4 on 2025-07-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_file_fields_from_processing_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='processinghistory',
            name='requester',
            field=models.CharField(blank=True, help_text='Token name that made the request', max_length=100, null=True),
        ),
    ]
