# Inventory
[all]
devhost ansible_connection=local
testhost ansible_connection=local


[all:vars]
# Common variables for all environments

server_name=172.30.4.69
ansible_user=seu-tools

ansible_ssh_private_key_file=/home/seu-tools/.ssh/id_ed25519
ansible_python_interpreter=/usr/bin/python3
python_version=python3.12
repo_url=git@github.com:SaudiElectronicUniversity/SEU_Tools.git

############################################################################################
####################### Pipeline Definition for SEU Tools ##################################

[Pipeline_Dev]
devhost

[Pipeline_Dev:vars]
#app_user=seu-tools-dev
app_dir=/opt/seu-tools-dev
deploy_env=Pipeline_Dev
gunicorn_port=8001
nginx_port=8080

[Pipeline_Test]
testhost

[Pipeline_Test:vars]
#app_user=seu-tools-test
app_dir=/opt/seu-tools-test
deploy_env=Pipeline_Test
gunicorn_port=8002
nginx_port=8081

###################################### End Pipeline Definition ######################################


# # Development environment
# [dev]
# localhost ansible_connection=local

# [dev:vars]
# app_user=seu-tools-dev
# app_dir=/opt/seu-tools-dev
# deploy_env=dev
# gunicorn_port=8001
# nginx_port=8080

#Testing environment
# [testing]
# localhost ansible_connection=local

# [testing:vars]
# app_user=seu-tools-test
# app_dir=/opt/seu-tools-testing
# deploy_env=test
# gunicorn_port=8002
# nginx_port=8081

# #Production environment
# [prod]
# localhost ansible_connection=local

# [prod:vars]
# app_user=seu-tools-prod
# app_dir=/opt/seu-tools-prod
# deploy_env=prod
# gunicorn_port=8000
# nginx_port=80